In [1]:
!git clone https://github.com/hchocobar/ucu_pad_project_2023_02.git

Cloning into 'ucu_pad_project_2023_02'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 3), reused 14 (delta 2), pack-reused 0
Receiving objects: 100% (15/15), 132.37 KiB | 16.55 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [2]:
import pandas as pd
import numpy as np

# Filter all warnings. If you would like to see the warnings, please comment the two lines below.
import warnings

warnings.filterwarnings('ignore')

Pregunta nro.1

In [3]:
path = "/content/ucu_pad_project_2023_02/assets/Energy Indicators.xls"
energy = pd.read_excel(path, skiprows=17, skipfooter=38)

In [4]:
energy = energy.iloc[:,2:]

# Renombrar las columnas
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

# Mostrar las primeras filas del DataFrame para verificar

In [5]:
energy['Energy Supply']= energy['Energy Supply'].apply(lambda x: x*1000000 if x!='...'else np.nan)
print(energy.head())

          Country  Energy Supply Energy Supply per Capita  % Renewable
0     Afghanistan   3.210000e+08                       10    78.669280
1         Albania   1.020000e+08                       35   100.000000
2         Algeria   1.959000e+09                       51     0.551010
3  American Samoa            NaN                      ...     0.641026
4         Andorra   9.000000e+06                      121    88.695650

In [6]:
energy['Energy Supply per Capita'] = energy['Energy Supply per Capita'].apply(lambda x: x if x!= "..."else np.nan)

print(energy.head())

          Country  Energy Supply  Energy Supply per Capita  % Renewable
0     Afghanistan   3.210000e+08                      10.0    78.669280
1         Albania   1.020000e+08                      35.0   100.000000
2         Algeria   1.959000e+09                      51.0     0.551010
3  American Samoa            NaN                       NaN     0.641026
4         Andorra   9.000000e+06                     121.0    88.695650

In [7]:


# Elimina parentesis
energy['Country'] = energy['Country'].str.replace(r"\s*\(.*\)", "", regex=True)
energy['Country'] = energy['Country'].str.replace(r"\d+$", "", regex=True)
energy["Country"]= energy["Country"].str.strip()
print(energy.head())

          Country  Energy Supply  Energy Supply per Capita  % Renewable
0     Afghanistan   3.210000e+08                      10.0    78.669280
1         Albania   1.020000e+08                      35.0   100.000000
2         Algeria   1.959000e+09                      51.0     0.551010
3  American Samoa            NaN                       NaN     0.641026
4         Andorra   9.000000e+06                     121.0    88.695650

In [8]:
energy["Country"].replace( {
    "Republic of Korea": "South Korea",
    "United States of America20": "United States",
    "United Kingdom of Great Britain and Northern Ireland19": "United Kingdom",
    "China, Hong Kong Special Administrative Region3": "Hong Kong",
    "China2":"China",
    "Japan10":"Japan",
    "France6": "France",
    "Italy9": "Italy",
    "Spain16": "Spain",
    "Autralia1": "Australia"
})

0                    Afghanistan
1                        Albania
2                        Algeria
3                 American Samoa
4                        Andorra
                 ...
222                     Viet Nam
223    Wallis and Futuna Islands
224                        Yemen
225                       Zambia
226                     Zimbabwe
Name: Country, Length: 227, dtype: object

In [9]:
path = "/content/ucu_pad_project_2023_02/assets/world_bank.csv"

# Cargar datos del PBI a un DataFrame
gdp = pd.read_csv(path, skiprows=4)

gdp["Country Name"].replace({
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
},inplace=True)

print(gdp.head())

  Country Name Country Code                            Indicator Name  \
0        Aruba          ABW  GDP at market prices (constant 2010 US$)
1      Andorra          AND  GDP at market prices (constant 2010 US$)
2  Afghanistan          AFG  GDP at market prices (constant 2010 US$)
3       Angola          AGO  GDP at market prices (constant 2010 US$)
4      Albania          ALB  GDP at market prices (constant 2010 US$)

   Indicator Code  1960  1961  1962  1963  1964  1965  ...          2006  \
0  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN
1  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...  4.018196e+09
2  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...  1.030523e+10
3  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...  5.581103e+10
4  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...  9.771760e+09

           2007          2008          2009          2010          2011  \
0           NaN           NaN           NaN  2.467704e+09           NaN
1  4.021331e+09  3.675728e+09  3.535389e+09  3.346317e+09  3.185605e+09
2  1.172119e+10  1.214448e+10  1.469733e+10  1.593680e+10  1.691113e+10
3  6.842044e+10  7.787420e+10  7.975320e+10  8.247091e+10  8.570262e+10
4  1.034829e+10  1.112752e+10  1.150029e+10  1.192695e+10  1.223109e+10

           2012          2013          2014          2015
0           NaN           NaN           NaN           NaN
1  3.129538e+09  3.127550e+09           NaN           NaN
2  1.935220e+10  1.973134e+10  1.999032e+10  2.029415e+10
3  9.012096e+10  9.626143e+10  1.008863e+11  1.039106e+11
4  1.240477e+10  1.254247e+10  1.279331e+10  1.312082e+10

[5 rows x 60 columns]

In [10]:
 path= "/content/ucu_pad_project_2023_02/assets/scimagojr-3.xlsx"
 scimago= pd.read_excel(path)
 scimago= scimago[scimago["Rank"]<=15]

In [11]:
#gdp = gdp.rename(columns={'Country Name': 'Country'})
#energy = energy.rename(columns={'Country Name': 'Country'})

In [12]:
def carga_datos():
  combinado = pd.merge(scimago, energy, how="inner", left_on="Country", right_on="Country")
  combinado = pd.merge(combinado, gdp, how="inner", left_on="Country", right_on="Country Name")
  columnas_requeridas = ["Country", "Rank", "Documents", "Citable documents", "Citations", "Self-citations", "Citations per document", "H index", "Energy Supply", "Energy Supply per Capita", "% Renewable", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"]
  combinado = combinado[columnas_requeridas]
  combinado.set_index('Country', inplace=True)
  return combinado
carga_datos()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

Pregunta 2

In [13]:
def outer():
  outer1 = pd.merge(scimago, energy, how="outer", left_on="Country", right_on="Country")
  outer1 = pd.merge(outer1, gdp, how="outer", left_on="Country", right_on="Country Name")
  cantidad = len(outer1)
  cantidad_combinado = len(carga_datos())
  resultado = cantidad - cantidad_combinado
  return resultado
outer()

297

Pregunta 3

In [14]:
def promedio_pbi():

  # Calcular promedio del PBI del 2006 al 2015
  gdp_columnas = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
  gdp_datos = gdp[gdp_columnas]
  avg = gdp_datos.mean(axis=1)
  avg_n = gdp[["Country Name"]].copy()
  avg_n ["Average GDP"]=avg
  avg_n = avg_n.sort_values(by="Average GDP",ascending=False)
  top15 = avg_n.head(15)
  avgGDP = top15.set_index("Country Name")["Average GDP"]
  return avgGDP
promedio_pbi()

Country Name
World                        6.713548e+13
High income                  4.586468e+13
OECD members                 4.514723e+13
Post-demographic dividend    4.292131e+13
IDA & IBRD total             2.202600e+13
Europe & Central Asia        2.117122e+13
Low & middle income          2.081219e+13
Middle income                2.051324e+13
IBRD only                    2.039738e+13
European Union               1.717367e+13
East Asia & Pacific          1.714490e+13
North America                1.703064e+13
Upper middle income          1.576611e+13
United States                1.536434e+13
Late-demographic dividend    1.389504e+13
Name: Average GDP, dtype: float64

Pregunta 4

In [15]:
def GDP_cambios():


  # 1. Selecciona el país con el sexto PIB promedio más grande
  sixth_country = promedio_pbi().index[5]
  GDP2006 = gdp[gdp["Country Name"]==sixth_country]["2006"].values[0]
  GDP2015 = gdp[gdp["Country Name"]==sixth_country]["2015"].values[0]
  GDP_cambio= GDP2015 - GDP2006
  return GDP_cambio
GDP_cambios()

1787625194095.8008

Pregunta 5

In [16]:
def energy_pc():
  avg= carga_datos()["Energy Supply per Capita"].mean()
  return avg
energy_pc()

144.41666666666666

Pregunta 6

In [17]:
def percent():

  max_renewable_country = carga_datos()['% Renewable'].idxmax()
  max_renewable_percentage = carga_datos().loc[max_renewable_country, '% Renewable']
  return (max_renewable_country, max_renewable_percentage)
percent()

('Brazil', 69.64803)

Pregunta 7

In [18]:
def relacion_columna():
  datosq = carga_datos()
  datosq["Citations Ratio"]=datosq["Self-citations"]/datosq["Citations"]
  maxid=datosq["Citations Ratio"].idxmax()
  max=datosq.loc[maxid, "Citations Ratio"]
  return (maxid, max)
relacion_columna()

('China', 0.6893126179389422)

Pregunta 8

In [19]:
def poblacion():
  poblacionq = carga_datos()
  poblacionq["Population"]=poblacionq["Energy Supply"] / poblacionq["Energy Supply per Capita"]
  poblacionq=poblacionq.sort_values(by="Population", ascending=False)
  tercer_pais=poblacionq.iloc[2].name
  return tercer_pais
poblacion()

'Brazil'

Pregunta 9

In [20]:
def citable_document():
  documentq = carga_datos()
  documentq["Citable document per Capita"]=documentq["Citable documents"]/documentq["Energy Supply per Capita"]
  correlacion= documentq["Citable documents"].corr(documentq["Energy Supply per Capita"])
  return correlacion
citable_document()

-0.1631406241128891

Pregunta 10

In [21]:
def high_renewable():
    datos = carga_datos()
    top15 = datos.head(15)
    median_renewable = top15['% Renewable'].median()
    datos['HighRenew'] = (datos['% Renewable'] >= median_renewable).astype(int)
    high_renew_series = datos.sort_values(by=['HighRenew', 'Rank'], ascending=[False, True])
    return high_renew_series
high_renewable()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,HighRenew
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,1
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,1
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,1
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,1
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,1
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0

Pregunta 11

In [22]:
def resumen_poblacion_por_continente():
    datos = carga_datos()
    datos["Population"] = datos["Energy Supply"] / datos["Energy Supply per Capita"]

    continent_dict = {
        'China': 'Asia',
        'United States': 'North America',
        'Japan': 'Asia',
        'United Kingdom': 'Europe',
        'Russian Federation': 'Europe',
        'Canada': 'North America',
        'Germany': 'Europe',
        'India': 'Asia',
        'France': 'Europe',
        'South Korea': 'Asia',
        'Italy': 'Europe',
        'Spain': 'Europe',
        'Iran': 'Asia',
        'Australia': 'Australia',
        'Brazil': 'South America'
    }

    datos['Continent'] = datos.index.map(continent_dict)
    resumen_continentes = datos.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std'])
    resumen_continentes = resumen_continentes.reset_index()
    resumen_continentes.columns = ['Continent', 'size', 'sum', 'mean', 'std']

    resumen_paises = datos[['Population']].reset_index()

    return resumen_continentes, resumen_paises

# Llamar a la función para obtener el resumen de población por continente y población estimada de cada país
resumen_continentes, resumen_paises = resumen_poblacion_por_continente()
print("Resumen por continente:")
print(resumen_continentes)
print("\nPoblación estimada de cada país:")
print(resumen_paises)

Resumen por continente:
       Continent  size           sum          mean           std
0           Asia     4  2.848861e+09  7.122152e+08  7.056123e+08
1      Australia     1  2.331602e+07  2.331602e+07           NaN
2         Europe     5  3.940587e+08  7.881174e+07  3.813228e+07
3  North America     1  3.523986e+07  3.523986e+07           NaN
4  South America     1  2.059153e+08  2.059153e+08           NaN

Población estimada de cada país:
               Country    Population
0                China  1.367645e+09
1                Japan  1.274094e+08
2   Russian Federation  1.435000e+08
3               Canada  3.523986e+07
4              Germany  8.036970e+07
5                India  1.276731e+09
6               France  6.383735e+07
7                Italy  5.990826e+07
8                Spain  4.644340e+07
9                 Iran  7.707563e+07
10           Australia  2.331602e+07
11              Brazil  2.059153e+08